### ISSUE TITLE
HPStrategyDCA has_bias

### ISSUE THREAD

**Issue by jifengthu** [mkajnar/HighProfitStrategy#1]
| filename      | strategy      | has_bias   |   total_signals |   biased_entry_signals |   biased_exit_signals | biased_indicators                                                  |
|---------------+---------------+------------+-----------------+------------------------+-----------------------+--------------------------------------------------------------------|
| HPStrategy.py | HPStrategyDCA | True       |              20 |                      0 |                     0 | bullish_divergence, fractal_top, fractal_bottom, turnaround_signal |

**Comment by jifengthu** [comment]
the command is： freqtrade lookahead-analysis -s HPStrategyDCA --timerange 20230101-

**Comment by mkajnar** [comment]
I will try your command. Can you explain it more, before it? :) Thanks bro.

**Comment by mkajnar** [comment]
![image](https://github.com/mkajnar/HighProfitStrategy/assets/5566514/7632a353-7e0a-4274-b392-ed512430e2aa)

Commited solution :) Again thanks bro. :)

**Comment by jifengthu** [comment]
You are welcome, great work!

**Comment by MuhammadElsaeed** [comment]
I run the same command against HPStrategyTFJPAConfirmV3.py and it seems it also has bias.
| filename                    | strategy                 | has_bias   |   total_signals |   biased_entry_signals |   biased_exit_signals | biased_indicators                                   |
|-----------------------------+--------------------------+------------+-----------------+------------------------+-----------------------+-----------------------------------------------------|
| HPStrategyTFJPAConfirmV3.py | HPStrategyTFJPAConfirmV3 | True       |              20 |                      8 |                     6 | fibonacci_retracements, lowest_price, highest_p

**Comment by CharlesJ-ABu** [comment]
> I run the same command against HPStrategyTFJPAConfirmV3.py and it seems it also has bias. | filename | strategy | has_bias | total_signals | biased_entry_signals | biased_exit_signals | biased_indicators | |-----------------------------+--------------------------+------------+-----------------+------------------------+-----------------------+-----------------------------------------------------| | HPStrategyTFJPAConfirmV3.py | HPStrategyTFJPAConfirmV3 | True | 20 | 8 | 6 | fibonacci_retracements, lowest_price, highest_p

I also countered with this issue in HPStrategyTF and I modified the code for higher_tf_trend with a shift(1) function and the bias disappeared, you can try to find the specific biased_indicators and shift the data
